import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputRoot = path.join(root, 'teams-captions-saver', '_locales');
const base = Object.freeze({
  extensionName: 'Better CaptionKeep — Live Meeting Transcript',
  extensionDescription: 'Local Teams, Meet, and Zoom transcripts with source-linked evidence and BYOAI—no bot, account, or AI subscription.',
  actionTitle: 'Better CaptionKeep — by Señor Farris',
  localizationQuality: 'reviewed',
  translationPreviewNotice: 'AI-assisted translation preview; not professionally certified. English is authoritative for privacy, security, and administration.',
  reportTranslation: 'Report this translation',
  followBrowserLanguage: 'Follow browser language',
  languageLabel: 'Language',
  settings: 'Settings',
  appearance: 'Appearance',
  theme: 'Theme',
  copyTranscript: 'Copy Transcript',
  saveTranscript: 'Save Transcript',
  viewTranscript: 'View Transcript',
  currentMeeting: 'Current meeting',
  transcript: 'Transcript',
  evidence: 'Evidence',
  privacyScrubber: 'Privacy Scrubber',
  startMicrosoftTranscript: 'Start Microsoft 365 transcript',
  close: 'Close',
  help: 'Help'
});

// AI-assisted preview strings. English fallback remains authoritative for keys
// that have not yet received a locale override.
const previews = {
  fr:{extensionDescription:'Capturez localement les sous-titres de réunion pour les examiner et les exporter en privé.',translationPreviewNotice:'Aperçu de traduction assistée par IA, non certifiée par un professionnel. L’anglais fait autorité pour la confidentialité, la sécurité et l’administration.',reportTranslation:'Signaler cette traduction',followBrowserLanguage:'Suivre la langue du navigateur',languageLabel:'Langue',settings:'Paramètres',copyTranscript:'Copier la transcription',viewTranscript:'Afficher la transcription'},
  es:{extensionDescription:'Captura subtítulos de reuniones localmente para revisarlos y exportarlos de forma privada.',translationPreviewNotice:'Vista previa de traducción asistida por IA, sin certificación profesional. El inglés es la referencia para privacidad, seguridad y administración.',reportTranslation:'Informar sobre esta traducción',followBrowserLanguage:'Usar el idioma del navegador',languageLabel:'Idioma',settings:'Configuración',copyTranscript:'Copiar transcripción',viewTranscript:'Ver transcripción'},
  es_419:{extensionDescription:'Captura subtítulos de reuniones localmente para revisarlos y exportarlos de forma privada.',translationPreviewNotice:'Vista previa de traducción asistida por IA, sin certificación profesional. El inglés es la referencia para privacidad, seguridad y administración.',reportTranslation:'Reportar esta traducción',followBrowserLanguage:'Usar el idioma del navegador',languageLabel:'Idioma',settings:'Configuración',copyTranscript:'Copiar transcripción',viewTranscript:'Ver transcripción'},
  de:{extensionDescription:'Meeting-Untertitel lokal erfassen, privat prüfen und exportieren.',translationPreviewNotice:'KI-gestützte Übersetzungsvorschau, nicht professionell zertifiziert. Für Datenschutz, Sicherheit und Administration ist Englisch maßgeblich.',reportTranslation:'Diese Übersetzung melden',followBrowserLanguage:'Browsersprache verwenden',languageLabel:'Sprache',settings:'Einstellungen',copyTranscript:'Transkript kopieren',viewTranscript:'Transkript anzeigen'},
  pt_BR:{extensionDescription:'Capture legendas de reuniões localmente para revisão e exportação privadas.',translationPreviewNotice:'Prévia de tradução assistida por IA, sem certificação profissional. O inglês é a referência para privacidade, segurança e administração.',reportTranslation:'Relatar esta tradução',followBrowserLanguage:'Usar o idioma do navegador',languageLabel:'Idioma',settings:'Configurações',copyTranscript:'Copiar transcrição',viewTranscript:'Ver transcrição'},
  pt_PT:{extensionDescription:'Capture legendas de reuniões localmente para revisão e exportação privadas.',translationPreviewNotice:'Pré-visualização de tradução assistida por IA, sem certificação profissional. O inglês é a referência para privacidade, segurança e administração.',reportTranslation:'Comunicar esta tradução',followBrowserLanguage:'Usar o idioma do navegador',languageLabel:'Idioma',settings:'Definições',copyTranscript:'Copiar transcrição',viewTranscript:'Ver transcrição'},
  it:{extensionDescription:'Acquisisci localmente i sottotitoli delle riunioni per revisione ed esportazione private.',translationPreviewNotice:'Anteprima di traduzione assistita dall’IA, non certificata professionalmente. L’inglese è il riferimento per privacy, sicurezza e amministrazione.',reportTranslation:'Segnala questa traduzione',followBrowserLanguage:'Segui la lingua del browser',languageLabel:'Lingua',settings:'Impostazioni',copyTranscript:'Copia trascrizione',viewTranscript:'Visualizza trascrizione'},
  nl:{extensionDescription:'Leg vergaderondertitels lokaal vast voor privécontrole en export.',translationPreviewNotice:'Voorbeeld van AI-ondersteunde vertaling, niet professioneel gecertificeerd. Engels is leidend voor privacy, beveiliging en beheer.',reportTranslation:'Deze vertaling melden',followBrowserLanguage:'Browsertaal volgen',languageLabel:'Taal',settings:'Instellingen',copyTranscript:'Transcript kopiëren',viewTranscript:'Transcript bekijken'},
  pl:{extensionDescription:'Przechwytuj napisy ze spotkań lokalnie do prywatnego przeglądania i eksportu.',translationPreviewNotice:'Podgląd tłumaczenia wspomaganego przez AI, bez profesjonalnej certyfikacji. Angielski jest miarodajny dla prywatności, bezpieczeństwa i administracji.',reportTranslation:'Zgłoś to tłumaczenie',followBrowserLanguage:'Użyj języka przeglądarki',languageLabel:'Język',settings:'Ustawienia',copyTranscript:'Kopiuj transkrypcję',viewTranscript:'Wyświetl transkrypcję'},
  cs:{extensionDescription:'Zachycujte titulky schůzek místně pro soukromou kontrolu a export.',translationPreviewNotice:'Náhled překladu s podporou AI bez profesionální certifikace. Pro soukromí, zabezpečení a správu je rozhodující angličtina.',reportTranslation:'Nahlásit tento překlad',followBrowserLanguage:'Použít jazyk prohlížeče',languageLabel:'Jazyk',settings:'Nastavení',copyTranscript:'Kopírovat přepis',viewTranscript:'Zobrazit přepis'},
  el:{extensionDescription:'Αποθηκεύστε τοπικά τους υπότιτλους συσκέψεων για ιδιωτικό έλεγχο και εξαγωγή.',translationPreviewNotice:'Προεπισκόπηση μετάφρασης με βοήθεια AI, χωρίς επαγγελματική πιστοποίηση. Τα αγγλικά αποτελούν την επίσημη αναφορά για απόρρητο, ασφάλεια και διαχείριση.',reportTranslation:'Αναφορά αυτής της μετάφρασης',followBrowserLanguage:'Χρήση γλώσσας προγράμματος περιήγησης',languageLabel:'Γλώσσα',settings:'Ρυθμίσεις',copyTranscript:'Αντιγραφή απομαγνητοφώνησης',viewTranscript:'Προβολή απομαγνητοφώνησης'},
  ro:{extensionDescription:'Capturați local subtitrările întâlnirilor pentru examinare și export privat.',translationPreviewNotice:'Previzualizare de traducere asistată de IA, fără certificare profesională. Engleza este referința pentru confidențialitate, securitate și administrare.',reportTranslation:'Raportați această traducere',followBrowserLanguage:'Urmați limba browserului',languageLabel:'Limbă',settings:'Setări',copyTranscript:'Copiază transcrierea',viewTranscript:'Vezi transcrierea'},
  sv:{extensionDescription:'Spara mötestexter lokalt för privat granskning och export.',translationPreviewNotice:'Förhandsvisning av AI-assisterad översättning, inte professionellt certifierad. Engelska är normerande för integritet, säkerhet och administration.',reportTranslation:'Rapportera översättningen',followBrowserLanguage:'Följ webbläsarens språk',languageLabel:'Språk',settings:'Inställningar',copyTranscript:'Kopiera transkription',viewTranscript:'Visa transkription'},
  uk:{extensionDescription:'Зберігайте субтитри зустрічей локально для приватного перегляду й експорту.',translationPreviewNotice:'Попередній переклад за допомогою ШІ без професійної сертифікації. Англійська версія є основною для конфіденційності, безпеки й адміністрування.',reportTranslation:'Повідомити про переклад',followBrowserLanguage:'Використовувати мову браузера',languageLabel:'Мова',settings:'Налаштування',copyTranscript:'Копіювати стенограму',viewTranscript:'Переглянути стенограму'},
  ru:{extensionDescription:'Сохраняйте субтитры встреч локально для частного просмотра и экспорта.',translationPreviewNotice:'Предварительный перевод с помощью ИИ без профессиональной сертификации. Английская версия является основной для конфиденциальности, безопасности и администрирования.',reportTranslation:'Сообщить о переводе',followBrowserLanguage:'Использовать язык браузера',languageLabel:'Язык',settings:'Настройки',copyTranscript:'Копировать стенограмму',viewTranscript:'Просмотреть стенограмму'},
  tr:{extensionDescription:'Toplantı altyazılarını özel inceleme ve dışa aktarma için yerel olarak kaydedin.',translationPreviewNotice:'Yapay zekâ destekli çeviri önizlemesi; profesyonel olarak onaylanmamıştır. Gizlilik, güvenlik ve yönetim için İngilizce esas alınır.',reportTranslation:'Bu çeviriyi bildir',followBrowserLanguage:'Tarayıcı dilini kullan',languageLabel:'Dil',settings:'Ayarlar',copyTranscript:'Transkripti kopyala',viewTranscript:'Transkripti görüntüle'},
  hi:{extensionDescription:'मीटिंग कैप्शन को निजी समीक्षा और निर्यात के लिए स्थानीय रूप से सहेजें।',translationPreviewNotice:'AI-सहायित अनुवाद पूर्वावलोकन; पेशेवर रूप से प्रमाणित नहीं। गोपनीयता, सुरक्षा और प्रशासन के लिए अंग्रेज़ी आधिकारिक संदर्भ है।',reportTranslation:'इस अनुवाद की रिपोर्ट करें',followBrowserLanguage:'ब्राउज़र की भाषा अपनाएँ',languageLabel:'भाषा',settings:'सेटिंग्स',copyTranscript:'प्रतिलेख कॉपी करें',viewTranscript:'प्रतिलेख देखें'},
  bn:{extensionDescription:'ব্যক্তিগত পর্যালোচনা ও রপ্তানির জন্য মিটিং ক্যাপশন স্থানীয়ভাবে সংরক্ষণ করুন।',translationPreviewNotice:'AI-সহায়িত অনুবাদ প্রিভিউ; পেশাদারভাবে প্রত্যয়িত নয়। গোপনীয়তা, নিরাপত্তা ও প্রশাসনের জন্য ইংরেজি প্রামাণ্য।',reportTranslation:'এই অনুবাদটি রিপোর্ট করুন',followBrowserLanguage:'ব্রাউজারের ভাষা অনুসরণ করুন',languageLabel:'ভাষা',settings:'সেটিংস',copyTranscript:'ট্রান্সক্রিপ্ট কপি করুন',viewTranscript:'ট্রান্সক্রিপ্ট দেখুন'},
  gu:{extensionDescription:'ખાનગી સમીક્ષા અને નિકાસ માટે મીટિંગ કૅપ્શન સ્થાનિક રીતે સાચવો.',translationPreviewNotice:'AI-સહાયિત અનુવાદ પૂર્વાવલોકન; વ્યાવસાયિક રીતે પ્રમાણિત નથી. ગોપનીયતા, સુરક્ષા અને વહીવટ માટે અંગ્રેજી અધિકૃત છે.',reportTranslation:'આ અનુવાદની જાણ કરો',followBrowserLanguage:'બ્રાઉઝરની ભાષા અનુસરો',languageLabel:'ભાષા',settings:'સેટિંગ્સ',copyTranscript:'ટ્રાન્સક્રિપ્ટ કૉપિ કરો',viewTranscript:'ટ્રાન્સક્રિપ્ટ જુઓ'},
  kn:{extensionDescription:'ಖಾಸಗಿ ಪರಿಶೀಲನೆ ಮತ್ತು ರಫ್ತಿಗಾಗಿ ಮೀಟಿಂಗ್ ಶೀರ್ಷಿಕೆಗಳನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಿ.',translationPreviewNotice:'AI ನೆರವಿನ ಅನುವಾದ ಪೂರ್ವವೀಕ್ಷಣೆ; ವೃತ್ತಿಪರ ಪ್ರಮಾಣೀಕರಣವಿಲ್ಲ. ಗೌಪ್ಯತೆ, ಭದ್ರತೆ ಮತ್ತು ಆಡಳಿತಕ್ಕೆ ಇಂಗ್ಲಿಷ್ ಅಧಿಕೃತ ಉಲ್ಲೇಖ.',reportTranslation:'ಈ ಅನುವಾದವನ್ನು ವರದಿ ಮಾಡಿ',followBrowserLanguage:'ಬ್ರೌಸರ್ ಭಾಷೆಯನ್ನು ಅನುಸರಿಸಿ',languageLabel:'ಭಾಷೆ',settings:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',copyTranscript:'ಪ್ರತಿಲಿಪಿ ನಕಲಿಸಿ',viewTranscript:'ಪ್ರತಿಲಿಪಿ ನೋಡಿ'},
  ml:{extensionDescription:'സ്വകാര്യ അവലോകനത്തിനും കയറ്റുമതിക്കും മീറ്റിംഗ് അടിക്കുറിപ്പുകൾ പ്രാദേശികമായി സൂക്ഷിക്കുക.',translationPreviewNotice:'AI സഹായിച്ച വിവർത്തന പ്രിവ്യൂ; പ്രൊഫഷണൽ സർട്ടിഫിക്കേഷൻ ഇല്ല. സ്വകാര്യത, സുരക്ഷ, ഭരണനിർവഹണം എന്നിവയ്ക്ക് ഇംഗ്ലീഷ് ആധികാരികമാണ്.',reportTranslation:'ഈ വിവർത്തനം റിപ്പോർട്ട് ചെയ്യുക',followBrowserLanguage:'ബ്രൗസർ ഭാഷ പിന്തുടരുക',languageLabel:'ഭാഷ',settings:'ക്രമീകരണങ്ങൾ',copyTranscript:'ട്രാൻസ്ക്രിപ്റ്റ് പകർത്തുക',viewTranscript:'ട്രാൻസ്ക്രിപ്റ്റ് കാണുക'},
  mr:{extensionDescription:'खाजगी पुनरावलोकन आणि निर्यातीसाठी मीटिंग कॅप्शन स्थानिकरित्या जतन करा.',translationPreviewNotice:'AI-सहाय्यित भाषांतर पूर्वावलोकन; व्यावसायिक प्रमाणित नाही. गोपनीयता, सुरक्षा आणि प्रशासनासाठी इंग्रजी अधिकृत संदर्भ आहे.',reportTranslation:'या भाषांतराची तक्रार करा',followBrowserLanguage:'ब्राउझरची भाषा वापरा',languageLabel:'भाषा',settings:'सेटिंग्ज',copyTranscript:'प्रतिलेख कॉपी करा',viewTranscript:'प्रतिलेख पहा'},
  ta:{extensionDescription:'தனிப்பட்ட மதிப்பாய்வு மற்றும் ஏற்றுமதிக்காக சந்திப்பு தலைப்புகளை உள்ளூரில் சேமிக்கவும்.',translationPreviewNotice:'AI உதவிய மொழிபெயர்ப்பு முன்னோட்டம்; தொழில்முறை சான்றிதழ் இல்லை. தனியுரிமை, பாதுகாப்பு மற்றும் நிர்வாகத்திற்கு ஆங்கிலமே அதிகாரப்பூர்வம்.',reportTranslation:'இந்த மொழிபெயர்ப்பைப் புகாரளிக்கவும்',followBrowserLanguage:'உலாவி மொழியைப் பின்பற்றவும்',languageLabel:'மொழி',settings:'அமைப்புகள்',copyTranscript:'உரையை நகலெடுக்கவும்',viewTranscript:'உரையைப் பார்க்கவும்'},
  te:{extensionDescription:'వ్యక్తిగత సమీక్ష మరియు ఎగుమతి కోసం సమావేశ క్యాప్షన్‌లను స్థానికంగా సేవ్ చేయండి.',translationPreviewNotice:'AI సహాయ అనువాద ప్రివ్యూ; వృత్తిపరంగా ధృవీకరించబడలేదు. గోప్యత, భద్రత మరియు పరిపాలనకు ఆంగ్లమే అధికారిక సూచన.',reportTranslation:'ఈ అనువాదాన్ని నివేదించండి',followBrowserLanguage:'బ్రౌజర్ భాషను అనుసరించండి',languageLabel:'భాష',settings:'సెట్టింగ్‌లు',copyTranscript:'ట్రాన్స్‌క్రిప్ట్ కాపీ చేయండి',viewTranscript:'ట్రాన్స్‌క్రిప్ట్ చూడండి'},
  id:{extensionDescription:'Simpan teks rapat secara lokal untuk ditinjau dan diekspor secara pribadi.',translationPreviewNotice:'Pratinjau terjemahan berbantuan AI; tidak bersertifikat profesional. Bahasa Inggris menjadi acuan untuk privasi, keamanan, dan administrasi.',reportTranslation:'Laporkan terjemahan ini',followBrowserLanguage:'Ikuti bahasa browser',languageLabel:'Bahasa',settings:'Setelan',copyTranscript:'Salin transkrip',viewTranscript:'Lihat transkrip'},
  fil:{extensionDescription:'I-save nang lokal ang mga caption ng pulong para sa pribadong pagsusuri at pag-export.',translationPreviewNotice:'Preview ng saling tinulungan ng AI; hindi propesyonal na sertipikado. Ingles ang opisyal na sanggunian para sa privacy, seguridad, at pamamahala.',reportTranslation:'Iulat ang saling ito',followBrowserLanguage:'Sundin ang wika ng browser',languageLabel:'Wika',settings:'Mga setting',copyTranscript:'Kopyahin ang transcript',viewTranscript:'Tingnan ang transcript'},
  ms:{extensionDescription:'Simpan kapsyen mesyuarat secara setempat untuk semakan dan eksport peribadi.',translationPreviewNotice:'Pratonton terjemahan berbantukan AI; tidak diperakui secara profesional. Bahasa Inggeris ialah rujukan untuk privasi, keselamatan dan pentadbiran.',reportTranslation:'Laporkan terjemahan ini',followBrowserLanguage:'Ikut bahasa pelayar',languageLabel:'Bahasa',settings:'Tetapan',copyTranscript:'Salin transkrip',viewTranscript:'Lihat transkrip'},
  th:{extensionDescription:'บันทึกคำบรรยายการประชุมไว้ในเครื่องเพื่อการตรวจสอบและส่งออกแบบส่วนตัว',translationPreviewNotice:'ตัวอย่างคำแปลที่ใช้ AI ช่วย ยังไม่ได้รับการรับรองโดยผู้เชี่ยวชาญ ภาษาอังกฤษเป็นข้อมูลอ้างอิงสำหรับความเป็นส่วนตัว ความปลอดภัย และการดูแลระบบ',reportTranslation:'รายงานคำแปลนี้',followBrowserLanguage:'ใช้ภาษาของเบราว์เซอร์',languageLabel:'ภาษา',settings:'การตั้งค่า',copyTranscript:'คัดลอกข้อความถอดเสียง',viewTranscript:'ดูข้อความถอดเสียง'},
  vi:{extensionDescription:'Lưu phụ đề cuộc họp cục bộ để xem xét và xuất riêng tư.',translationPreviewNotice:'Bản xem trước dịch thuật có AI hỗ trợ, chưa được chứng nhận chuyên nghiệp. Tiếng Anh là bản tham chiếu cho quyền riêng tư, bảo mật và quản trị.',reportTranslation:'Báo cáo bản dịch này',followBrowserLanguage:'Theo ngôn ngữ trình duyệt',languageLabel:'Ngôn ngữ',settings:'Cài đặt',copyTranscript:'Sao chép bản chép lời',viewTranscript:'Xem bản chép lời'},
  ja:{extensionDescription:'会議の字幕をローカルに保存し、非公開で確認およびエクスポートできます。',translationPreviewNotice:'AI支援翻訳のプレビューであり、専門家による認証はありません。プライバシー、セキュリティ、管理については英語版が正式な参照です。',reportTranslation:'この翻訳を報告',followBrowserLanguage:'ブラウザーの言語に従う',languageLabel:'言語',settings:'設定',copyTranscript:'文字起こしをコピー',viewTranscript:'文字起こしを表示'},
  ko:{extensionDescription:'회의 자막을 로컬에 저장하여 비공개로 검토하고 내보냅니다.',translationPreviewNotice:'AI 지원 번역 미리보기이며 전문 번역 인증을 받지 않았습니다. 개인정보 보호, 보안 및 관리에 대해서는 영어가 공식 기준입니다.',reportTranslation:'이 번역 신고',followBrowserLanguage:'브라우저 언어 사용',languageLabel:'언어',settings:'설정',copyTranscript:'대화 내용 복사',viewTranscript:'대화 내용 보기'},
  zh_CN:{extensionDescription:'在本地保存会议字幕，以便私下查看和导出。',translationPreviewNotice:'这是 AI 辅助翻译预览，未经专业认证。隐私、安全和管理内容以英文为准。',reportTranslation:'报告此翻译',followBrowserLanguage:'使用浏览器语言',languageLabel:'语言',settings:'设置',copyTranscript:'复制文字记录',viewTranscript:'查看文字记录'},
  zh_TW:{extensionDescription:'在本機儲存會議字幕，以便私下檢閱和匯出。',translationPreviewNotice:'這是 AI 輔助翻譯預覽，未經專業認證。隱私、安全和管理內容以英文為準。',reportTranslation:'回報此翻譯',followBrowserLanguage:'使用瀏覽器語言',languageLabel:'語言',settings:'設定',copyTranscript:'複製文字記錄',viewTranscript:'檢視文字記錄'},
  ar:{extensionDescription:'احفظ تسميات الاجتماع التوضيحية محليًا للمراجعة والتصدير بشكل خاص.',translationPreviewNotice:'معاينة ترجمة بمساعدة الذكاء الاصطناعي وغير معتمدة مهنيًا. النص الإنجليزي هو المرجع للخصوصية والأمان والإدارة.',reportTranslation:'الإبلاغ عن هذه الترجمة',followBrowserLanguage:'استخدام لغة المتصفح',languageLabel:'اللغة',settings:'الإعدادات',copyTranscript:'نسخ النص',viewTranscript:'عرض النص'},
  he:{extensionDescription:'שמירת כתוביות פגישה באופן מקומי לצורך בדיקה וייצוא פרטיים.',translationPreviewNotice:'תצוגה מקדימה של תרגום בסיוע AI, ללא אישור מקצועי. האנגלית היא המקור הקובע לפרטיות, אבטחה וניהול.',reportTranslation:'דיווח על התרגום',followBrowserLanguage:'שימוש בשפת הדפדפן',languageLabel:'שפה',settings:'הגדרות',copyTranscript:'העתקת תמלול',viewTranscript:'הצגת תמלול'},
  fa:{extensionDescription:'زیرنویس‌های جلسه را برای بررسی و خروجی خصوصی به‌صورت محلی ذخیره کنید.',translationPreviewNotice:'پیش‌نمایش ترجمه با کمک هوش مصنوعی و بدون تأیید حرفه‌ای است. متن انگلیسی مرجع حریم خصوصی، امنیت و مدیریت است.',reportTranslation:'گزارش این ترجمه',followBrowserLanguage:'پیروی از زبان مرورگر',languageLabel:'زبان',settings:'تنظیمات',copyTranscript:'کپی رونوشت',viewTranscript:'نمایش رونوشت'},
  sw:{extensionDescription:'Hifadhi manukuu ya mkutano kwenye kifaa kwa ukaguzi na uhamishaji wa faragha.',translationPreviewNotice:'Onyesho la awali la tafsiri iliyosaidiwa na AI, halijathibitishwa kitaalamu. Kiingereza ndicho rejea kwa faragha, usalama na usimamizi.',reportTranslation:'Ripoti tafsiri hii',followBrowserLanguage:'Fuata lugha ya kivinjari',languageLabel:'Lugha',settings:'Mipangilio',copyTranscript:'Nakili nakala',viewTranscript:'Tazama nakala'}
};

function catalog(messages, quality) {
  return Object.fromEntries(Object.entries({...base, ...messages, localizationQuality:quality})
    .map(([key, message]) => [key, {message}]));
}

await mkdir(outputRoot, {recursive:true});
await mkdir(path.join(outputRoot, 'en'), {recursive:true});
await writeFile(path.join(outputRoot, 'en', 'messages.json'), `${JSON.stringify(catalog({}, 'reviewed'), null, 2)}\n`, 'utf8');
for (const [locale, messages] of Object.entries(previews)) {
  const dir = path.join(outputRoot, locale);
  await mkdir(dir, {recursive:true});
  await writeFile(path.join(dir, 'messages.json'), `${JSON.stringify(catalog(messages, 'preview'), null, 2)}\n`, 'utf8');
}
console.log(`Generated ${Object.keys(previews).length + 1} locale catalogs in ${outputRoot}`);
